import { Agency } from "./types";

export const mockAgencies: Agency[] = [
  {
    id: "1",
    nombre: "Turismo Caribe",
    email: "info@turismocaribe.com",
    estados: ["Carabobo", "Lara", "Aragua"],
    mediaViajes: 45,
    status: "activo",
    tipo: "pro",
  },
  {
    id: "2",
    nombre: "Viajes Andinos",
    email: "contacto@viajesandinos.com",
    estados: ["Mérida", "Táchira"],
    mediaViajes: 32,
    status: "activo",
    tipo: "pendiente",
  },
  {
    id: "3",
    nombre: "Costa Azul Tours",
    email: "ventas@costaazultours.ve",
    estados: ["Falcón", "Aragua", "Carabobo", "Miranda"],
    mediaViajes: 67,
    status: "activo",
    tipo: "pro",
  },
  {
    id: "4",
    nombre: "Expediciones Guayana",
    email: "info@expedicionesguayana.com",
    estados: ["Bolívar"],
    mediaViajes: 28,
    status: "activo",
    tipo: "standard",
  },
  {
    id: "5",
    nombre: "Turismo Oriental",
    email: "reservas@turismoriental.ve",
    estados: ["Sucre", "Anzoátegui", "Nueva Esparta"],
    mediaViajes: 52,
    status: "inactivo",
    tipo: "standard",
  },
  {
    id: "6",
    nombre: "Aventura Extrema",
    email: "aventura@extrema.com",
    estados: ["Mérida", "Barinas"],
    mediaViajes: 38,
    status: "activo",
    tipo: "pendiente",
  },
  {
    id: "7",
    nombre: "Playas del Sol",
    email: "contacto@playasdelsol.ve",
    estados: ["Falcón", "Vargas"],
    mediaViajes: 71,
    status: "activo",
    tipo: "pro",
  },
  {
    id: "8",
    nombre: "Rutas Coloniales",
    email: "info@rutascoloniales.com",
    estados: ["Zulia", "Trujillo", "Lara"],
    mediaViajes: 29,
    status: "activo",
    tipo: "standard",
  },
  {
    id: "9",
    nombre: "Ecoturismo Verde",
    email: "reservas@ecoturismoverde.ve",
    estados: ["Amazonas", "Bolívar"],
    mediaViajes: 19,
    status: "activo",
    tipo: "pendiente",
  },
  {
    id: "10",
    nombre: "Turismo Capital",
    email: "ventas@turismocapital.com",
    estados: ["Miranda", "Distrito Capital", "Vargas"],
    mediaViajes: 83,
    status: "activo",
    tipo: "pro",
  },
  {
    id: "11",
    nombre: "Safari Llanos",
    email: "info@safarillanos.ve",
    estados: ["Apure", "Guárico"],
    mediaViajes: 24,
    status: "inactivo",
    tipo: "standard",
  },
  {
    id: "12",
    nombre: "Viajes Premium",
    email: "contacto@viajespremium.com",
    estados: ["Carabobo", "Miranda", "Zulia", "Lara"],
    mediaViajes: 91,
    status: "activo",
    tipo: "pro",
  },
  {
    id: "13",
    nombre: "Destinos Tropicales",
    email: "reservas@destinostropicales.ve",
    estados: ["Sucre", "Nueva Esparta"],
    mediaViajes: 56,
    status: "activo",
    tipo: "standard",
  },
  {
    id: "14",
    nombre: "Montaña y Aventura",
    email: "info@montanayaventura.com",
    estados: ["Mérida"],
    mediaViajes: 41,
    status: "activo",
    tipo: "pendiente",
  },
  {
    id: "15",
    nombre: "Turismo Express",
    email: "ventas@turismoexpress.ve",
    estados: ["Aragua", "Carabobo"],
    mediaViajes: 62,
    status: "activo",
    tipo: "standard",
  },
];
