import { User } from "./types";

export const mockUsers: User[] = [
  {
    id: "1",
    nombre: "María González",
    email: "maria.gonzalez@email.com",
    rol: "usuario",
    estado: "Miranda",
    fechaRegistro: "15/01/2024",
    status: "activo",
    reservasRealizadas: 12,
  },
  {
    id: "2",
    nombre: "Carlos Rodríguez",
    email: "carlos.rodriguez@email.com",
    rol: "usuario",
    estado: "Carabobo",
    fechaRegistro: "22/01/2024",
    status: "activo",
    reservasRealizadas: 8,
  },
  {
    id: "3",
    nombre: "Ana Martínez",
    email: "ana.martinez@turismocaribe.com",
    rol: "agencia",
    estado: "Lara",
    fechaRegistro: "10/12/2023",
    status: "activo",
    reservasRealizadas: 156,
  },
  {
    id: "4",
    nombre: "Luis Hernández",
    email: "luis.hernandez@email.com",
    rol: "usuario",
    estado: "Zulia",
    fechaRegistro: "05/02/2024",
    status: "activo",
    reservasRealizadas: 3,
  },
  {
    id: "5",
    nombre: "Admin Sistema",
    email: "admin@tripealo.com",
    rol: "admin",
    estado: "Distrito Capital",
    fechaRegistro: "01/11/2023",
    status: "activo",
    reservasRealizadas: 0,
  },
  {
    id: "6",
    nombre: "Isabel Pérez",
    email: "isabel.perez@email.com",
    rol: "usuario",
    estado: "Aragua",
    fechaRegistro: "18/01/2024",
    status: "inactivo",
    reservasRealizadas: 5,
  },
  {
    id: "7",
    nombre: "Roberto Silva",
    email: "roberto.silva@viajesandinos.com",
    rol: "agencia",
    estado: "Mérida",
    fechaRegistro: "12/01/2024",
    status: "activo",
    reservasRealizadas: 89,
  },
  {
    id: "8",
    nombre: "Carmen Torres",
    email: "carmen.torres@email.com",
    rol: "usuario",
    estado: "Falcón",
    fechaRegistro: "25/01/2024",
    status: "activo",
    reservasRealizadas: 15,
  },
  {
    id: "9",
    nombre: "Diego Ramírez",
    email: "diego.ramirez@email.com",
    rol: "usuario",
    estado: "Bolívar",
    fechaRegistro: "30/01/2024",
    status: "activo",
    reservasRealizadas: 7,
  },
  {
    id: "10",
    nombre: "Patricia López",
    email: "patricia.lopez@costaazul.ve",
    rol: "agencia",
    estado: "Carabobo",
    fechaRegistro: "08/12/2023",
    status: "activo",
    reservasRealizadas: 234,
  },
  {
    id: "11",
    nombre: "Fernando Díaz",
    email: "fernando.diaz@email.com",
    rol: "usuario",
    estado: "Sucre",
    fechaRegistro: "12/02/2024",
    status: "activo",
    reservasRealizadas: 19,
  },
  {
    id: "12",
    nombre: "Laura Castro",
    email: "laura.castro@email.com",
    rol: "usuario",
    estado: "Anzoátegui",
    fechaRegistro: "03/02/2024",
    status: "inactivo",
    reservasRealizadas: 2,
  },
  {
    id: "13",
    nombre: "Miguel Vargas",
    email: "miguel.vargas@expediciones.com",
    rol: "agencia",
    estado: "Bolívar",
    fechaRegistro: "20/01/2024",
    status: "activo",
    reservasRealizadas: 67,
  },
  {
    id: "14",
    nombre: "Sandra Morales",
    email: "sandra.morales@email.com",
    rol: "usuario",
    estado: "Miranda",
    fechaRegistro: "16/02/2024",
    status: "activo",
    reservasRealizadas: 11,
  },
  {
    id: "15",
    nombre: "Javier Ruiz",
    email: "javier.ruiz@email.com",
    rol: "usuario",
    estado: "Lara",
    fechaRegistro: "09/02/2024",
    status: "activo",
    reservasRealizadas: 6,
  },
  {
    id: "16",
    nombre: "Gabriela Núñez",
    email: "gabriela.nunez@playasdelsol.ve",
    rol: "agencia",
    estado: "Falcón",
    fechaRegistro: "15/12/2023",
    status: "activo",
    reservasRealizadas: 178,
  },
  {
    id: "17",
    nombre: "Ricardo Mendoza",
    email: "ricardo.mendoza@email.com",
    rol: "usuario",
    estado: "Táchira",
    fechaRegistro: "28/01/2024",
    status: "activo",
    reservasRealizadas: 9,
  },
  {
    id: "18",
    nombre: "Valentina Rojas",
    email: "valentina.rojas@email.com",
    rol: "usuario",
    estado: "Nueva Esparta",
    fechaRegistro: "07/02/2024",
    status: "activo",
    reservasRealizadas: 14,
  },
];
